### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by eirhor** [olemak/themebuilder#2]
Noticed that no linting rules are available, should add this before making it open source, so that future contributors have a ruleset to follow. Will likely require a run through on most of the code to ensure it's correctly linted before launch.

Suggestion for presets that should be applied:
- the latest recommended eslint rules.
- the airbnb rules.
- airbnb react rules.

Rules that might need to be overridden:
- indent: should be 4 spaces.
- max-length: should be unlimited or longer than 100 characters at least, maybe double?

**Comment by eirhor** [comment]
@olemak want me to take a look at it?

**Comment by olemak** [comment]
@eirhor Yes please!

**Comment by olemak** [comment]
@eirhor Note that I ejected from create-react-app

**Comment by olemak** [comment]
Done!
Using Prettyer for autofprmating now, so line lengths are usally pretty nice and readable.
